[package]
name = "powerpointrs"
version = "0.1.0"
edition = "2021"

[lib]
name = "powerpointrs"
path = "src/lib/mod.rs"

[[bin]]
name = "pptbin"
path = "src/bin.rs"

[[bin]]
name = "pptwasm"
path = "src/wasm/mod.rs"

[profile.release]
strip = "symbols"
